# Minio group
- name: Minio healthchecks pass
  uri:
    #    curl -G -v localhost:8500/v1/health/checks/minio --data-urlencode 'filter=(Status=="passing")'
    url: http://localhost:8500/v1/health/checks/minio?filter={{ '(Status=="passing")' | urlencode }}
    method: GET
    return_content: yes
    status_code: 200
    body_format: json
  register: result_minio
  retries: 15
  delay: 15
  until: result_minio.json | length == 2
- name: Response body result_minio
  debug: msg="Here {{ (result_minio.json) }}"

#  Hive group
- name: Hive-database healthchecks pass
  uri:
    #    curl -G -v localhost:8500/v1/health/checks/hive-database --data-urlencode 'filter=(Status=="passing")'
    url: http://localhost:8500/v1/health/checks/hive-database?filter={{ '(Status=="passing")' | urlencode }}
    method: GET
    return_content: yes
    status_code: 200
    body_format: json
  register: result_hive_database
  retries: 20
  delay: 30
  until: result_hive_database.json | length == 1
- name: Response body result_hive_database
  debug: msg="Here {{ (result_hive_database.json) }}"

- name: Hive-metastore healthchecks pass
  uri:
    #    curl -G -v localhost:8500/v1/health/checks/hive-metastore --data-urlencode 'filter=(Status=="passing")'
    url: http://localhost:8500/v1/health/checks/hive-metastore?filter={{ '(Status=="passing")' | urlencode }}
    method: GET
    return_content: yes
    status_code: 200
    body_format: json
  register: result_hive_metastore
  retries: 30
  delay: 30
  until: result_hive_metastore.json | length == 1
- name: Response body result_hive_metastore
  debug: msg="Here {{ (result_hive_metastore.json) }}"

- name: Hive-server healthchecks pass
  uri:
    #    curl -G -v localhost:8500/v1/health/checks/hive-server --data-urlencode 'filter=(Status=="passing")'
    url: http://localhost:8500/v1/health/checks/hive-server?filter={{ '(Status=="passing")' | urlencode }}
    method: GET
    return_content: yes
    status_code: 200
    body_format: json
  register: result_hive_server
  retries: 20
  delay: 30
  until: result_hive_server.json | length == 2
- name: Response body result_hive_server
  debug: msg="Here {{ (result_hive_server.json) }}"

- name: Presto healthchecks pass
  uri:
    #    curl -G -v localhost:8500/v1/health/checks/hive-server --data-urlencode 'filter=(Status=="passing")'
    url: http://localhost:8500/v1/health/checks/presto?filter={{ '(Status=="passing")' | urlencode }}
    method: GET
    return_content: yes
    status_code: 200
    body_format: json
  register: result_presto
  retries: 20
  delay: 30
  until: result_presto.json | length == 3
- name: Response body result_presto
  debug: msg="Here {{ (result_presto.json) }}"

- name: Testdata-csv healthchecks pass
  uri:
    #    curl -G -v localhost:8500/v1/health/checks/hive-server --data-urlencode 'filter=(Status=="passing")'
    url: http://localhost:8500/v1/health/checks/testdata-csv?filter={{ '(Status=="passing")' | urlencode }}
    method: GET
    return_content: yes
    status_code: 200
    body_format: json
  register: result_testdata_csv
  retries: 20
  delay: 30
  until: result_testdata_csv.json | length == 2
- name: Response body result_testdata_csv
  debug: msg="Here {{ (result_testdata_csv.json) }}"
