name: Tests

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Super-Linter
        uses: github/super-linter@v3.14.4

  full-stack:
    needs: linter
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      # Runs make test
      - name: Run make test
        run: make test